from pathlib import Path
from docx import Document
import copy,json
w=Path(__file__).parent;r=w/'audit_replay_threshold_station_20260918';p=r/'Documents/CG_MainText_ReplayVerified.docx';d=Document(p)
changes={
'Each 6,000×3 CSV waveform was converted':'We matched 6,000×3 CSV waveforms to STEAD using SHA-256 hashes of little-endian float32 values in column-major E/N/Z order. Exhaustive hashing of all 1,265,657 local HDF5 waveform datasets found exactly one trace for each of the 2,234 distinct selected fingerprints, without conflicting source assignments. Upstream metadata agreed throughout. The mapping and partitions were frozen before v2 training; exhaustive uniqueness verification followed training. This establishes exact matches in this archive version, not near-duplicate absence or catalogue identity accuracy.',
'Identity correction and rerun.':'Identity correction and rerun. The original ordinal metadata join misidentified waveforms: 151/335 historical test records shared physical sources with training. We corrected identities and reran all 106 fits. Current test records previously belonged to training (233), validation (46) or testing (51); 196/221 current test sources had historical training/validation membership. Thus source disjointness in v2 does not establish independent confirmation. Because population allocation and training also changed, old-to-new scores cannot isolate leakage-induced inflation (Supplementary Tables S22–S23).',
'Reference arrivals were converted':'Reference arrivals became Gaussian phase targets (equation 4; Zhu and Beroza, 2019; Mousavi et al., 2020). Both arrivals have manual metadata status in 1,224/1,544 training, 306/360 validation and 287/330 test records. The other 417 records include automatic/autopicker status. Manual-only sensitivity restricts evaluation without retraining or independently validating annotations (Supplementary Tables S24–S25).',
'Recovered test metadata contain':'Test metadata contain 64 network–receiver keys across 23 networks; PB contributes 99/330 records. Fifty-five test keys also occur in training, covering 318 records. Nine keys absent from training and validation contain only 12 records from ten sources. These are retrospective strata, not a station-held-out design; keys do not distinguish station epochs (Supplementary Tables S12 and S26).',
'DP = G. Report':'DP = G. Return tS = t̂S for accepted S and NaN otherwise; an empty DS returns no pick. The S–P rule constrains ordering rather than learning a physical objective. Detected-only scoring retains the accepted-P gate. Peak 0.30, quality 3 and the 0.1–30 s window occur in July and September configurations (Supplementary Table S20), but their earliest calibration data remain unknown. No validation-only calibration is asserted. Before sensitivity calculations, we specified a 27-setting grid: peak {0.20, 0.30, 0.40}, tied P/S quality {2, 3, 4}, and maximum S–P {20, 30, 40} s. Minimum separation remains 0.1 s and the uncertain boundary half the peak threshold. All 18 full stackers and six baseline fits retain the original primary setting. Window changes also alter the S quality denominator; accepted scoring is invariant to quality threshold.',
'In equation 12, Nd':'In equation 12, Nd counts accepted finite picks; coverage Nd/N differs from recall and detected-only coverage. Expanded stacking summaries average meta seeds within each base and then the three base means. Between-base SD uses those three means, not nine independent replicates; baseline summaries use three fits. Paired intervals use 10,000 NumPy default_rng source-cluster draws (seed 42), retaining every record of each sampled source. Per-fit F1 is recomputed before averaging, with common draws across comparisons. Intervals condition on fixed models and split; they exclude training, partition and separate station-level uncertainty. Subset diagnostics resample their stated sources. Intervals are exploratory and pointwise, without family-wise or false-discovery-rate control. No configuration is selected from the threshold grid. Base-42 summaries retain their three-meta-seed scope.',
'Fresh GPU inference replay loaded':'Fresh GPU replay loaded all 106 checkpoints and rebuilt inputs from waveform CSVs. Across six mode/base combinations, 18,528 original/augmented OOF tensors and 1,980 test meta tensors matched their caches exactly (tolerance 1e-6). All 70 prediction sets × 330 records reproduced constrained and unconstrained pick times and statuses without mismatches (time tolerance 1e-7 s). Saved validation-derived ensemble weights were retained. This verifies fixed-artifact inference and feature reconstruction, not retraining determinism or independent predictive validation (Supplementary Table S21).',
'No recovered earthquake source is shared':'Current train, validation and test sources are disjoint, but historical exposure remains. Only 25 test sources (26 records) lack historical training/validation membership; all previously occurred in testing. No development-naive subset is established. Historical scores are not a valid source-held-out comparator, and the changed allocation and training prevent a controlled estimate of leakage inflation.',
'Manual-reference evaluation retained':'On 287 both-phase manual records from 188 sources, stacking S Full3C-minus-Z-only ΔF1 was 0.2705 [0.2113, 0.3299], positive in all nine paired fits; PhaseNetMatched gave 0.2550 [0.2013, 0.3085]. This supports subset consistency, not annotation-error immunity. Both intervals included zero in the 20-record manual/no-historical-train-validation intersection, which still had historical test exposure (Supplementary Table S25; Fig. S6).',
'Station stratification is also descriptive.':'Station stratification remains descriptive: the 12 records at nine currently unseen network–receiver keys provide only ten source clusters. Their S method-comparison intervals include zero and cannot establish station transfer (Supplementary Table S26).',
'Across the predefined decoder grid, accepted S':'Across the predefined grid, accepted S Full3C-minus-Z-only ΔF1 ranged from 0.2839–0.2856 for stacking and 0.2862–0.2873 for PhaseNetMatched; all pointwise intervals were positive. Quality invariance reduces accepted scoring to nine peak/window combinations. Detected-only ranges were 0.2855–0.3031 and 0.2828–0.2875. The baseline P advantage persisted throughout. Accepted S method intervals included zero throughout, whereas 18/27 detected-only Z-only S intervals favoured the baseline. Stacking P component intervals depended on scoring policy (Supplementary Table S27; Fig. S7). These fixed-model diagnostics neither select a new operating point nor establish historical calibration provenance.',
'The real-data verification now links':'Real-data verification links 2,234 unique waveform matches to source-disjoint checkpoint memberships and fresh inference. OOF/test tensors matched exactly, with zero pick/status mismatches across 70 prediction sets. Independent calculations reproduced 1,260 metric rows; 25,248 manifest entries matched 2,336 input files (Supplementary Table S21). These computational checks do not make historically reused observations independent validation data.',
'The study is limited to one retrospectively':'The study uses one retrospectively recovered STEAD subset and fixed split. Initialization repetitions and source bootstrapping exclude partition and training uncertainty; base-42 ablations lack replication at other base seeds. Meta fits share OOF features, and outer validation is reused for base selection, meta stopping and ensemble weighting. Most current test sources had historical training/validation exposure. Manual-reference sensitivity does not quantify annotation error, and the unavailable extraction recipe limits assessment of selection bias. Twelve unseen-key records cannot establish station transfer. Threshold sensitivity does not prove validation-only calibration; multiple intervals remain exploratory. Regional transfer, continuous-stream false alarms, overlapping events and operational latency were not evaluated.',
'Further validation requires observations':'Confirmation requires data outside prior research and development; another split of this population cannot erase historical exposure. Additional source splits can measure partition sensitivity, while nested validation separates selection stages. Independent datasets, matched official picker implementations, continuous-record false alarms, latency and controlled perturbations remain necessary tests of transfer and mechanism.',
'The corrected workflow connects uniquely':'The workflow links uniquely matched local STEAD identities, source-disjoint partitions, checkpoint memberships, fresh inference and reproducible metrics. The S component-access difference persists across tested initializations and manual-reference evaluation. Historical exposure remains; station, regional and independent-dataset generalization are not established.',
'On 330 records from 221 sources held':'On 330 records from 221 sources held out from v2 fitting and validation, accepted stacking P/S F1@100 ms was 0.8268/0.5536 for Full3C and 0.8134/0.2686 for Z-only. Between-base SDs were 0.0069/0.0127 and 0.0073/0.0152. Full3C accepted-pick MAE was 166.62/610.29 ms, with coverage 99.06%/98.01%. Acceptance combines detected and uncertain picks.',
'The stacking S component-access difference':'The S component difference was 0.2850 [0.2293, 0.3418]. PhaseNetMatched achieved P/S F1 of 0.9833/0.5857 (Full3C) and 0.9833/0.2995 (Z-only); primary intervals support its P advantage but include zero for both S method differences. Base-42 ablations support exploratory S context/dilation gains without isolating nonlinearity. Confirmation requires data kept outside prior development.',
'The corrected mapping and source protocol':'The corrected mapping and protocol identify current inputs; label quantization and prediction-based verification are documented. The exhaustive fingerprint index verifies exact-match multiplicity in the local HDF5 version, not other STEAD versions. Recovery establishes retained records but not the unavailable original extraction procedure. Historical roles and all threshold/station outputs accompany the audit.'}
seen=[]
for para in d.paragraphs:
 for prefix,text in changes.items():
  if para.text.startswith(prefix):
   fmt=copy.deepcopy(para.runs[0]._r.rPr) if para.runs and para.runs[0]._r.rPr is not None else None
   para.clear();run=para.add_run(text)
   if fmt is not None:run._r.insert(0,fmt)
   para.paragraph_format.line_spacing=2
   seen.append(prefix);break
assert set(seen)==set(changes),(set(changes)-set(seen));d.save(p)
start=next(i for i,p in enumerate(d.paragraphs) if 'Introduction' in p.text and p.style.name.startswith('Heading'));end=next(i for i,p in enumerate(d.paragraphs) if p.text.strip()=='References')
count=sum(len(p.text.split()) for p in d.paragraphs[start:end] if not p.text.startswith(('Fig.','Table ')))
(r/'main_text_length.json').write_text(json.dumps(dict(words_intro_through_declarations_excluding_captions_tables=count,paragraphs_condensed=len(seen),details_retained_in_supplement=True),indent=2));print('BODY WORDS',count)
