function [tFull, tZonly] = loadLockedPredictionTables(config)
% loadLockedPredictionTables.m
% PURPOSE: Load locked Full 3C and Z-only prediction CSVs.
%          Prefer existing prediction CSVs; do NOT read waveform CSVs.
% INPUTS:  config -- framework config
% OUTPUTS: tFull, tZonly -- MATLAB tables with all prediction columns
% ASSUMPTIONS: predictions were generated by the locked pipeline and are unchanged.

predDir = fullfile(config.outputFolder, 'predictions');

pathFull  = fullfile(predDir, 'predictions_full3C.csv');
pathZonly = fullfile(predDir, 'predictions_Zonly.csv');

if ~isfile(pathFull)
    error('loadLockedPredictionTables: predictions_full3C.csv not found at %s', pathFull);
end
tFull = readtable(pathFull, 'VariableNamingRule','preserve');
fprintf('  [Load] Full 3C: %d records from %s\n', height(tFull), pathFull);

if isfile(pathZonly)
    tZonly = readtable(pathZonly, 'VariableNamingRule','preserve');
    fprintf('  [Load] Z-only : %d records from %s\n', height(tZonly), pathZonly);
else
    tZonly = table();
    fprintf('  [Load] Z-only predictions not found -- Z-only audit will be skipped.\n');
end
end
